import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "@fontsource/bebas-neue";
import styled from "styled-components";

export const Center = styled.div`
  margin-top: 100px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
`;
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Center>
        <Image
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/2560px-International_Pok%C3%A9mon_logo.svg.png"
          alt="pokemon-logo"
          width="500"
          height="200"
        />
      </Center>
    </div>
  );
}
